# Generated by Django 5.2.3 on 2025-06-17 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_reservas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservas',
            new_name='Booking',
        ),
    ]
