# Generated by Django 5.2.1 on 2025-06-18 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_booking_no_of_guest_alter_booking_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='title',
            new_name='item',
        ),
    ]
