# Generated by Django 5.2.1 on 2025-06-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_rename_title_menu_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='item',
            new_name='title',
        ),
    ]
